name: Bump version

on:
  push:
    branches:
      - master  # another branch could be specified here

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'bump')"
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2
        with:
          token: {% raw %} '${{ secrets.PERSONAL_ACCESS_TOKEN }}' {% endraw %}
          fetch-depth: 0

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install pipenv invoke
          inv env.init-dev

      # do not failed when there is not versioning needed (e.g., document change)
      - name: Create bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          inv git.bump

      - name: Push changes
        uses: Woile/github-push-action@master
        with:
          github_token: {% raw %} ${{ secrets.PERSONAL_ACCESS_TOKEN }} {% endraw %}
          tags: "true"
